/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/computer.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.01, 0]}>
        <mesh geometry={nodes.base.geometry} material={materials.corpo_notebook} position={[0, 0.01, 0]} />
        <mesh
          geometry={nodes.tela.geometry}
          material={materials.tela1}
          position={[0, 0.12, -0.15]}
          rotation={[-1.82, 0, 0]}
        />
        <mesh geometry={nodes.teclado.geometry} position = {[0,0.001,0]}scale={1.15} >
        <meshStandardMaterial
            attach="material" // How the element should attach itself to its parent
            //color="grey"
            color= {"#787878"}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/computer.glb')
