/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations, useTexture} from '@react-three/drei'

export default function Model(props) {
  const [resumeTexture] = useTexture(['/res.png']);
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/resume.glb')
  const { actions } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Paper2"
        geometry={nodes.Paper2.geometry}
        position={[0, -0.03, -0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.03}
      >
        <meshBasicMaterial attach="material" map={resumeTexture} />

        </mesh>
    </group>
  )
}

useGLTF.preload('/resume.glb')
